const font = {
    size: '16px',
    family: "Poppins",
};

const colors = {
    sesame: '#202020',
    plum: '#4F1C48',
    ocean: '#304A81',
    neon: '#D6E307',
    eggshell: '#D8D8D8',
}

/**
 * Font sizes generated by:
 * https://type-scale.com/
 */

const GlobalTheme = {
    breakpoints: ['33.75em', '48em', '68.75em'],
    // space: [0, 4, 8, 16, 32, 64, 128, 256, 512],
    fonts: {
        body: `${font.family}, sans-serif`,
        heading: 'inherit',
    },
    fontSizes: ['0.75rem', '1rem', '1.05rem', '1.563rem', '1.952rem', '2.441rem', '3.052rem'],
    fontWeights: {
        body: 300,
        bold: 500,
    },
    lineHeights: {
        body: 1.65,
        heading: 1.15,
    },
    colors: {
        text: colors.eggshell,
        background: colors.sesame,
        primary: colors.neon,
    },
    text: {
        heading: {
            lineHeight: 'heading',
        },
    },
    styles: {
        layout: {
            display: 'flex',
            justifyContent: 'center',
            margin: '0 auto',
            padding: '0 73px',
        },
        root: {
            lineHeight: 'body',
            fontWeight: 'body',
            fontSize: 1
        },
        h1: {
            variant: 'text.heading',
            fontSize: 6,
            lineHeight: '3.125rem'
        },
        h2: {
            variant: 'text.heading',
            fontSize: 5,
        },
        h3: {
            variant: 'text.heading',
            fontSize: 4,
        },
        h4: {
            variant: 'text.heading',
            fontSize: 3,
        },
        h5: {
            variant: 'text.heading',
            fontSize: 2,
        },
        small: {
            fontSize: 0,
        },
        a: {
            color: 'primary'
        },
    }
}
const BlogTheme = {
    ...GlobalTheme,
    colors: {
        text: colors.sesame,
        background: colors.eggshell,
        primary: colors.plum
    },
}

export { GlobalTheme, BlogTheme };